# Root and standard stuff --> could be quickly a Ansible-galaxy role with 'nicorama' as template variable
- hosts: test
  # remote_user: root  # must be root on gandi
  remote_user: root

    #############
    #
    #  Here are a list of YAML commands
    #
    #############


    # A docker file already exists, needs docker.io : http://stackoverflow.com/questions/27978324
  tasks:
  #    - apt_repository: repo='ppa:webupd8team/java'
      - apt_repository: repo='ppa:openjdk-r/ppa'
      - name: install_java
        apt: name=openjdk-8-jdk state=present update_cache=yes
        tags: [java]
      - name: install_java
        apt: name=maven state=present update_cache=yes
        tags: [java]




